n = int(input('Informe um número inteiro: '))
x = 0
print('TABUADA DO {0}\n{0} x {1} = {2}'.format(n, x, n*x))
x += 1
print('{0} x {1} = {2}'.format(n, x, n*x))
x += 1
print('{0} x {1} = {2}'.format(n, x, n*x))
x += 1
print('{0} x {1} = {2}'.format(n, x, n*x))
x += 1
print('{0} x {1} = {2}'.format(n, x, n*x))
x += 1
print('{0} x {1} = {2}'.format(n, x, n*x))
x += 1
print('{0} x {1} = {2}'.format(n, x, n*x))
x += 1
print('{0} x {1} = {2}'.format(n, x, n*x))
x += 1
print('{0} x {1} = {2}'.format(n, x, n*x))
x += 1
print('{0} x {1} = {2}'.format(n, x, n*x))
x += 1
print('{0} x {1} = {2}'.format(n, x, n*x))